### ISSUE TITLE
feat(jsonpointer): be able to pass `Weakpointer` to `PositionTracker::get`

### ISSUE THREAD

**Issue by tony-go** [sourcemeta/jsontoolkit#1362]
## Goal

```cc
  sourcemeta::jsontoolkit::PositionTracker tracker;
  sourcemeta::jsontoolkit::parse(input, std::ref(tracker));

  sourcemeta::jsontoolkit::WeakPointer pointer_1;
  EXPECT_EQ(tracker.get(pointer_1).value(),
            sourcemeta::jsontoolkit::PositionTracker::Position({1, 1, 7, 1}));
```

## Tries

I already tried a few things

1. Change [`Pointer`](https://github.com/sourcemeta/jsontoolkit/blob/main/src/jsonpointer/include/sourcemeta/jsontoolkit/jsonpointer_position.h#L46) to a template type but then it degrade the DX as I have to specify the "type" of `PostionTracker<T>` I want ...
2. Add a new `::get` method which takes explicitly a `WeakPointer` - But I did not succed to convert the WeakPointer to a pointer ... (Maybe @jviotti has an idea...)
3. I change the whole `Pointer` to be a `WeakPointer`, then I got this weird error:
   ```shell
    /Users/tonygo/oss/jsontoolkit/test/jsonpointer/jsonpointer_position_test.cc:30:50: note: in instantiation of member function 'sourcemeta::jsontoolkit::GenericToken<std::reference_wrapper<const std::string>, sourcemeta::jsontoolkit::FastHash<sourcemeta::jsontoolkit::JSON>>::GenericToken' requested here
   30 |   sourcemeta::jsontoolkit::WeakPointer pointer_3{"0", "foo"};
````

Not sure about the best approach, my 2cents is that the internal of `PositionTracker` should not be correlate to `Pointer` we should be able to pass whatever we want: ei https://github.com/sourcemeta/jsontoolkit/blob/main/src/jsonpointer/include/sourcemeta/jsontoolkit/jsonpointer_position.h#L64

**Comment by jviotti** [comment]
At least as a note for my future self next week: we can probably make the corresponding method a templated method and just let it take anything that looks like a pointer. Might elegantly solve the entire issue

**Comment by jviotti** [comment]
@tony-go I ended up extending the `to_pointer` utility to be able to convert weak pointers to non-weak pointers. Please take a look at the referenced PR. I think that will be more than enough for now! Just convert the weak pointers before accessing the trackers!
